### ISSUE TITLE
Android reports shown (partly) as iOS

### ISSUE THREAD

**Issue by oferRounds** [Buglife/react-native-buglife#14]
See here. Happened since we moved to Buglife for React Native

Example: 
http://buglife.com/r/bob-a2da90d4-af10-4d48-9b8e-c0c4183b582e-test-881453

Notice the combination of iOS 9 + OnePlus

<img width="889" alt="screen shot 2019-01-31 at 13 29 56" src="https://user-images.githubusercontent.com/1477963/52051516-7d3ed700-255c-11e9-8cc3-75688fdb5988.png">

**Comment by oferRounds** [comment]
Should probably be "Android 9"

**Comment by oferRounds** [comment]
@danhd123 can you have a look here?

**Comment by danhd123** [comment]
Fixed.
