### ISSUE TITLE
On iOS, apps require Info.plist to be updated to with NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by ArnaudRinquin** [Buglife/react-native-buglife#5]
I tried to publish a build but received an email from Apple prompting me to specify how we use pictures.

<img width="828" alt="screen shot 2018-01-05 at 18 38 21" src="https://user-images.githubusercontent.com/228886/34635666-c11561b8-f247-11e7-8475-87766bb357b0.png">

I quickly realized it was due to Buglife (our app does not use any photo API).

It'd be nice to add a recipe in the README.

**Comment by schukin** [comment]
Thanks @ArnaudRinquin! We've updated the README.
