### ISSUE TITLE
iOS at runtime - dyld: Libray not loaded: @rpath/Buglife.framework/Buglife

### ISSUE THREAD

**Issue by ArnaudRinquin** [Buglife/react-native-buglife#8]
<img width="818" alt="screen shot 2018-01-25 at 10 51 01" src="https://user-images.githubusercontent.com/228886/35406893-0126adda-01bf-11e8-91f5-3d04888d7b7b.png">

I had to follow [these steps](https://stackoverflow.com/a/30979099/1265207) to overcome the issue. Not sure if this can be automated but it should be documented (unless maybe if it is only required on legacy/already setup projects)

**Comment by danhd123** [comment]
Hi @ArnaudRinquin, it looks like this is probably from having previously had Buglife installed via Cocoapods. Sorry about that. None of our test projects have required following the linked steps.

**Comment by oferRounds** [comment]
Hey Dave, that could be the case, but what was the fix? I have removed Buglife via CocoaPods before installing via NPM. 

I was able to make the crash gone by manually adding it to the `Embedded Binaries` section on Xcode (as stated above), but on Android, the app still keeps crushing...

**Comment by schukin** [comment]
@oferRounds - I’ve reopened the following issue for tracking this Android issue you’re seeing. https://github.com/Buglife/react-native-buglife/issues/10

**Comment by axeldelafosse** [comment]
Hey guys! I'm commenting this issue because I installed Buglife via npm and get a SIGABRT on iOS when launching my app on my device. I had to manually add `Buglife.framework` to the `Embedded Binaries` to make it work! No problem on Android...
